FROM resin/rpi-raspbian

RUN apt-get update
RUN apt-get upgrade
RUN apt-get install npm
RUN apt-get install nodejs-legacy
RUN npm install http-server -g

EXPOSE 3000

CMD http-server /app -c-1 --cors -p 3000